language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - coverage run -m pytest -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master

